var lines = [
  "REALISATION:",
  "Vincent Cailly",
  "     ",
  "https://github.com/Totobriac/Totobriac.github.io",
  "Site réalisé en Vanilla JS",
  "  ",
  "RESSOURCES:",
  "-Franks Laboratory Youtube",
  "-Stackoverflow",
  "-Lodev.org",
  "  ",
  "CREDITS:",
  "Iggy Pop - Lust for life: 9 Bit Tribute Band",
  "David Bowie - Starman [8-bit]: TimTheHuman",
  "Himno Argentino: Jonysniuk",
  "The Velvet Underground - Sunday Morning: Paul Scott",
  "Guns & Roses - Welcome to the Jungle:  8 Bit Universe",
  "Bon Jovi - Livin' On A Prayer [8 Bit]: 8 Bit Universe",
  "The Strokes - Barely Legal 8-Bit: The 8-Bit Operator",
  "Bobby Prince - Searching for the enemy",
  "Bobby Prince - P.O.W",
  "Derrick Theme - 8bit version: Rallymen007",
  "",
  "SPRITES:",
  "www.gamedeveloperstudio.com/",
  "www.spriters-resource.com/",
  "",
  "CONTACT:",
  "contact@vincentcailly.com",
  "https://www.linkedin.com/in/vincentcailly/",

]

export { lines };
